/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class etomica_potential_amoeba_PotentialTinker */

#ifndef _Included_etomica_potential_amoeba_PotentialTinker
#define _Included_etomica_potential_amoeba_PotentialTinker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     etomica_potential_amoeba_PotentialTinker
 * Method:    tinkerEnergy
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_etomica_potential_amoeba_PotentialTinker_tinkerEnergy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
